spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:sid
spring.datasource.driverClassName=org.h2.Driver
aws.region=us-east-1
spring.h2.console.settings.web-allow-others=true
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.0-flash
spring.ai.chat.memory.repository.jdbc.initialize-schema=embedded
minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}